version: "3.8"
services:
  flutter-app:
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    network_mode: host
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir 
    privileged: true
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
      - /dev/bus/usb:/dev/bus/usb # LINUX ONLY

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
